// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.28;

/// @notice The Merkle root hashes of each FRI folding round.
/// @dev roots[0] is the root of the original polynomial tree; roots[k] is the root after k folds.
struct FriCommitment {
    uint256[] roots;
}

/// @notice A Merkle proof for one leaf in a FRI tree.
struct MerkleProof {
    /// @dev The opened leaf values (one per committed polynomial).
    uint256[] leaf;
    /// @dev The sibling hashes along the Merkle path from leaf to root (root not included).
    uint256[] path;
}

/// @notice The left/right Merkle proof pair for one FRI folding round.
struct FriQueryRound {
    MerkleProof left;
    MerkleProof right;
}

/// @notice A complete FRI query covering all folding rounds.
/// @dev n is the number of committed evaluations (power of two).
/// @dev index is the queried leaf index in [0, n).
/// @dev rounds[0] proves the original polynomial tree; rounds[k] proves the k-th folded tree.
struct FriQuery {
    uint256 n;
    uint256 index;
    FriQueryRound[] rounds;
}

/// @title FriVerifier
/// @notice Verifies FRI queries generated by the Rust `libernet` crate with the Sha2Hash backend.
/// @dev Compatible with the `Sha2Hash`-backed FRI prover in `crypto/src/fri.rs`.
///      All field arithmetic is performed in the BlueSky prime field
///      p = 0x7ffffffffffffffffffffffffffffffe0673ddf29e9b5547c000000000000001.
library FriVerifier {
    uint256 constant P =
        0x7ffffffffffffffffffffffffffffffe0673ddf29e9b5547c000000000000001;

    /// @dev 2^256 mod P; needed to reduce the 512-bit double-SHA256 output to a field element.
    uint256 constant TWO_256_MOD_P =
        0x00000000000000000000000000000003f318441ac2c955707ffffffffffffffe;

    /// @dev Domain separators derived offline via SHA3-512("libernet/fri/<tag>") mod P.
    ///      Not reproducible in the EVM; hardcoded from the Rust implementation.
    uint256 constant LEAF_DST =
        0x6ade565de4068c14b708c2aeb582b747d8159fd173dd4ecb32ef2d54683e2cfe;
    uint256 constant TREE_DST =
        0x17a4e1d7f96a99904bcf07467db89f654d651724f57c477d41c52418c3aa6783;
    uint256 constant FOLD_DST =
        0x21e331ad95b69e952c269e82b37c9e470942d5379584f7a0e311481b7ad77942;

    /// @dev inv(5) mod P — inverse of the multiplicative generator of the BlueSky field.
    uint256 constant GENERATOR_INV =
        0x3333333333333333333333333333333268fb25943f71554fe666666666666667;

    /// @dev (P+1)/2 mod P — the multiplicative inverse of 2.
    uint256 constant TWO_INV =
        0x3fffffffffffffffffffffffffffffff0339eef94f4daaa3e000000000000001;

    /// @dev Inverse of the primitive 2^62-th root of unity in the BlueSky field.
    uint256 constant ROOT_OF_UNITY_INV =
        0x76def406f046ef5ee7eeecd2c4e6ecd7cdedc4e2bcf6b19f1420121cd00b4cdb;

    /// @dev The 2-adicity of P-1: P-1 = 2^62 * T for odd T.
    uint256 constant S = 62;

    /// @notice Hashes two scalars with a domain separator using double-SHA256.
    /// @dev lo = uint256(SHA256(uint256(0) || dst || a || b)) (big-endian interpretation).
    ///      hi = uint256(SHA256(uint256(1) || dst || a || b)).
    ///      result = (lo + hi * 2^256) mod P.
    ///      Matches `Sha2Hash::hash_raw` in the Rust implementation.
    function hashRaw(
        uint256 dst,
        uint256 a,
        uint256 b
    ) internal pure returns (uint256) {
        uint256 lo = uint256(sha256(abi.encodePacked(uint256(0), dst, a, b)));
        uint256 hi = uint256(sha256(abi.encodePacked(uint256(1), dst, a, b)));
        return addmod(lo, mulmod(hi, TWO_256_MOD_P, P), P);
    }

    /// @notice Hashes a variable-length array of scalars using double-SHA256.
    /// @dev lo = SHA256(uint256(0) || inputs[0] || ... || inputs[n-1]).
    ///      hi = SHA256(uint256(1) || inputs[0] || ... || inputs[n-1]).
    ///      result = (lo + hi * 2^256) mod P.
    ///      Matches `Sha2Hash::hash_many` in the Rust implementation.
    function hashMany(uint256[] memory inputs) internal pure returns (uint256) {
        uint256 n = inputs.length;
        bytes memory lo_data = new bytes(32 * (n + 1));
        bytes memory hi_data = new bytes(32 * (n + 1));
        assembly {
            mstore(add(hi_data, 32), 1)
            for {
                let i := 0
            } lt(i, n) {
                i := add(i, 1)
            } {
                let val := mload(add(add(inputs, 32), mul(i, 32)))
                mstore(add(add(lo_data, 64), mul(i, 32)), val)
                mstore(add(add(hi_data, 64), mul(i, 32)), val)
            }
        }
        uint256 lo = uint256(sha256(lo_data));
        uint256 hi = uint256(sha256(hi_data));
        return addmod(lo, mulmod(hi, TWO_256_MOD_P, P), P);
    }

    /// @notice Hashes a leaf of a FRI Merkle tree.
    /// @dev Prepends LEAF_DST and the leaf length before hashing:
    ///      hash_many([LEAF_DST, len(values), values[0], ..., values[n-1]]).
    ///      Matches `hash_leaf::<Sha2Hash>` in the Rust implementation.
    function hashLeaf(uint256[] memory values) internal pure returns (uint256) {
        uint256 numInputs = 2 + values.length;
        uint256[] memory inputs = new uint256[](numInputs);
        inputs[0] = LEAF_DST;
        inputs[1] = values.length;
        for (uint256 i = 0; i < values.length; i++) {
            inputs[i + 2] = values[i];
        }
        return hashMany(inputs);
    }

    /// @notice Verifies a Merkle proof against a root hash.
    /// @param proof The leaf values and sibling path hashes.
    /// @param index The leaf index (used to determine left/right at each tree level).
    /// @param rootHash The expected Merkle root to verify against.
    /// @return True iff the proof is valid.
    function verifyMerklePath(
        MerkleProof memory proof,
        uint256 index,
        uint256 rootHash
    ) internal pure returns (bool) {
        uint256 hash = hashLeaf(proof.leaf);
        for (uint256 j = 0; j < proof.path.length; j++) {
            uint256 sibling = proof.path[j];
            if (index & 1 != 0) {
                hash = hashRaw(TREE_DST, sibling, hash);
            } else {
                hash = hashRaw(TREE_DST, hash, sibling);
            }
            index >>= 1;
        }
        return index == 0 && hash == rootHash;
    }

    /// @notice Returns true iff all committed polynomials in the proof witness a constant.
    /// @dev A leaf proof is constant when every sibling hash equals the running leaf hash,
    ///      which happens when all domain positions share the same committed value.
    ///      Matches `LeafProof::is_constant` in the Rust implementation.
    function isConstant(MerkleProof memory proof) internal pure returns (bool) {
        uint256 hash = hashLeaf(proof.leaf);
        for (uint256 j = 0; j < proof.path.length; j++) {
            if (proof.path[j] != hash) {
                return false;
            }
            hash = hashRaw(TREE_DST, hash, hash);
        }
        return true;
    }

    /// @dev Computes base^exponent mod P via the modexp precompile (EIP-198, address 0x05).
    function _pow(
        uint256 base,
        uint256 exponent
    ) internal view returns (uint256 result) {
        assembly {
            let ptr := mload(0x40)
            mstore(ptr, 0x20)
            mstore(add(ptr, 0x20), 0x20)
            mstore(add(ptr, 0x40), 0x20)
            mstore(add(ptr, 0x60), base)
            mstore(add(ptr, 0x80), exponent)
            mstore(add(ptr, 0xa0), P)
            if iszero(staticcall(gas(), 5, ptr, 0xc0, ptr, 0x20)) {
                revert(0, 0)
            }
            result := mload(ptr)
        }
    }

    /// @dev Returns floor(log2(n)) for n >= 1.
    function _log2(uint256 n) internal pure returns (uint256 result) {
        while (n > 1) {
            n >>= 1;
            result++;
        }
    }

    /// @notice Verifies a FRI query against a commitment.
    /// @dev Matches `Query<Sha2Hash>::verify` in the Rust implementation. The caller is
    ///      responsible for checking that `query.n` equals the committed domain size and that
    ///      `query.rounds.length` equals the expected number of folding rounds.
    /// @param query The FRI query (opening proof) to verify.
    /// @param commitment The FRI commitment containing the Merkle root of each folding round.
    function verifyQuery(
        FriQuery memory query,
        FriCommitment memory commitment
    ) internal view {
        uint256 n = query.n;
        uint256 index = query.index;
        FriQueryRound[] memory rounds = query.rounds;
        uint256[] memory roots = commitment.roots;

        uint256 h = rounds.length;
        uint256 k = _log2(n);
        require(h == roots.length, "round count mismatch");
        require(h > 0, "empty proof");
        require(h <= k + 1, "invalid proof size");

        uint256[] memory pos = rounds[0].left.leaf;
        uint256 step = _pow(ROOT_OF_UNITY_INV, 1 << (S - k));

        uint256 m = n;
        for (uint256 r = 0; r < h; r++) {
            MerkleProof memory left = rounds[r].left;
            MerkleProof memory right = rounds[r].right;
            uint256 rootHash = roots[r];

            require(left.path.length == _log2(m), "invalid left proof height");
            require(
                right.path.length == _log2(m),
                "invalid right proof height"
            );
            require(left.leaf.length == pos.length, "leaf length mismatch");
            for (uint256 i = 0; i < pos.length; i++) {
                require(left.leaf[i] == pos[i], "leaf value mismatch");
            }

            require(
                verifyMerklePath(left, index, rootHash),
                "left Merkle proof failed"
            );
            require(
                verifyMerklePath(right, (index + m / 2) % m, rootHash),
                "right Merkle proof failed"
            );

            uint256 omega_inv_i = _pow(step, index);
            uint256 alpha = mulmod(
                hashRaw(FOLD_DST, rootHash, 0),
                GENERATOR_INV,
                P
            );

            m /= 2;
            index %= m;

            uint256[] memory next_pos = new uint256[](pos.length);
            for (uint256 i = 0; i < pos.length; i++) {
                uint256 p = pos[i];
                uint256 ng = right.leaf[i];
                uint256 diff = addmod(p, P - ng, P);
                next_pos[i] = mulmod(
                    addmod(
                        addmod(p, ng, P),
                        mulmod(mulmod(alpha, omega_inv_i, P), diff, P),
                        P
                    ),
                    TWO_INV,
                    P
                );
            }
            pos = next_pos;
            step = mulmod(step, step, P);
        }

        require(
            isConstant(rounds[h - 1].left),
            "final left polynomial is not constant"
        );
        require(
            isConstant(rounds[h - 1].right),
            "final right polynomial is not constant"
        );
    }
}
